### ISSUE TITLE
Add RDS to our infrastructure

### ISSUE THREAD

**Issue by MikhailShumenko** [architecture-playground/terraform-playground#4]
Learn about PostgreSQL
Create simple RDS instance of PostgreSQL (cluster is optional)

**Comment by BulgakovAnton** [comment]
:clock1: 4h 30m
Today I recalled working with postgres.  run db in the docker, connected to it, snapped the terminal work with her.

**Comment by BulgakovAnton** [comment]
:clock1: 7h Today I continued to study postgres. Created databases, users, roles, and tables. Added and deleted data. I made a selection by parameters

**Comment by BulgakovAnton** [comment]
:clock1: 7h
Today I learned how to backup a database. Create two containers on one created a backup file transferred to another. And he began to deal with the connection through the idea

**Comment by BulgakovAnton** [comment]
:clock1: 6h
Today I dealt with users of postgres. Creating tables and backup.

**Comment by BulgakovAnton** [comment]
:clock1: 6h 
Today I made a backup of the database and connected to the containers through the idea and created a cluster of RDS

**Comment by BulgakovAnton** [comment]
:clock1: 7h 30m
Today I studied the setup of vpn, I manually created a new VPC. Created RDS Instance connected it to the VPC. Deepened knowledge at VPC and vpn. I am sure that I will connect to the RDS on Monday.

**Comment by BulgakovAnton** [comment]
:clock1: 7h
I configured AWS Site-to-Site VPN today

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Today, I was finally able to connect to my RDS. The whole problem was in the wrong security group settings. He began to deal with vpn. I will continue tomorrow.

**Comment by BulgakovAnton** [comment]
:clock1: 6h
Today I learned how to connect to an RDS instance from a computer. I created another VPC for connecting to which I entered my IP.

**Comment by BulgakovAnton** [comment]
:clock1: 5h 30m
Today I studied the gateways, what are the differences between nat and the internet. Create an RDS instance with a new automatically created VPC. Created Security Group

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Today I connected to the RDS and after that, I studied how to configure VPN in AWS.

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Today I better understood how VPN works. Created his open VPN on ec2 instance. Tomorrow we will create in AWS Site-to-Site VPN

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Today I created AWS Site To Site VPN figured out Route. and read about peering.

**Comment by BulgakovAnton** [comment]
:clock1: 6h
Today I studied VPC peering and routes how to configure and interact between VPC

**Comment by BulgakovAnton** [comment]
:clock1: 5h
Today I deal with routing and peering. And how are requests to the RDS

**Comment by BulgakovAnton** [comment]
:clock1: 7h
Today I created VPC Peering in another VPC and connected to the database through it.

**Comment by BulgakovAnton** [comment]
:clock1: 7h 30m
Today I configured OpenVPN on ec2 instance.

**Comment by BulgakovAnton** [comment]
:clock: 0h
I did not work today because I am still in the hospital

**Comment by BulgakovAnton** [comment]
:clock: 0h
I did not work today because I am still in the hospital

**Comment by BulgakovAnton** [comment]
:clock1: 5h
Read and learn about iptables

**Comment by BulgakovAnton** [comment]
:clock1: 6h
Today I created VPC, Nginx, portable, hello-world.

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Studied Nginx and how requests are redirected

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Today I studied certificates SSL.

**Comment by BulgakovAnton** [comment]
Today I studied certificates SSL and started reading about DNS.

**Comment by BulgakovAnton** [comment]
I didn't work today, I was in the hospital all day

**Comment by BulgakovAnton** [comment]
:clock1: 4h 
today I read about:
Amazon Elastic Transcoder
AWS Elemental MediaConvert

**Comment by MikhailShumenko** [comment]
Looks can be Closed. We already have a simple RDS instance, so the task is done.
